package sstrange;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;

import sstrange.matchgenerator.ComparisonPairTuple;

public class IndexHTMLGenerator {

	public static void generateHtml(String assignmentRootPath, ArrayList<ComparisonPairTuple> codePairs,
			String coreTemplateHTMLPath, String outputDirPath, double threshold, String languageCode) throws Exception {

		String tableContent = getTableContent(codePairs, languageCode);

		String logoHeader = "<div class=\"embedimage\" style=\"width:15%;margin-left:0px;\">\r\n"
				+ "					<img class=\"embedimage\" src=\"strange_html_layout_additional_files/logo.png\" alt=\"logo STRANGE\">\r\n"
				+ "				</div>";

		// create directory
		File dirRoot = new File(outputDirPath);
		if (dirRoot.exists() == false)
			dirRoot.mkdir();

		// generate the html page
		File templateFile = new File(coreTemplateHTMLPath);
		File outputFile = new File(outputDirPath + File.separator + "index.html");
		BufferedReader fr = new BufferedReader(new FileReader(templateFile));
		BufferedWriter fw = new BufferedWriter(new FileWriter(outputFile));
		String line;
		while ((line = fr.readLine()) != null) {

			if (line.contains("@filepath")) {
				line = line.replace("@filepath", assignmentRootPath);
			}

			if (line.contains("@logo")) {
				line = line.replace("@logo", logoHeader);
			}

			if (line.contains("@about")) {
				line = line.replace("@about", (languageCode.equals("en")) ? getAboutEn() : getAboutID());
			}

			if (line.contains("@threshold")) {
				line = line.replace("@threshold", String.format("%.0f", threshold));
			}

			if (line.contains("@tablecontent")) {
				line = line.replace("@tablecontent", tableContent);
			}

			if (line.contains("@explanation"))
				line = line.replace("@explanation",
						(languageCode.equals("en")) ? getExplanationContentEn() : getExplanationContentID());

			fw.write(line);
			fw.write(System.lineSeparator());
		}
		fr.close();
		fw.close();
	}

	private static String getExplanationContentID() {
		String s = "";

		s += "<ul>";
		s += "<li>Kesamaan yang dilaporkan adalah kesamaan rerata, yang mempertimbangkan semua perbedaan dalam perhitungannya.</li>";
		s += "<li>Kesamaan standar mengabaikan perbedaan di komentar, spasi, dan nilai konstanta. "
				+ "Perbedaan di nama identifier (misal variabel atau fungsi) diabaikan di Java, Python, C#, PHP, JavaScript dan CSS (terbatas pada nama variabel dan selectors). "
				+ "Perbedaan di konten teks, tag script, tag style, dan kapitalisasi di nama tag diabaikan di HTML. "
				+ "Perbedaan di tipe data primitif diabaikan di Java.</li>";
		s += "<li>Kesamaan sensitif memperhitungkan token apa adanya tanpa generalisasi.</li>";
		s = s + "</ul>\n";

		return s;
	}

	private static String getExplanationContentEn() {
		String s = "";

		s += "<ul>";
		s += "<li>The reported similarity is average similarity, which considers all differences in its calculation.</li>";
		s += "<li>Standard similarity ignores differences in comments, white space, and constants. "
				+ "Differences in identifier names (e.g., variables or functions) are ignored in Java, Python, C#, PHP, JavaScript and CSS (limited to variable names and selectors). "
				+ "Differences in text content, script tag, style tag, and capitalisation in tag names are ignored in HTML. "
				+ "Differences in primitive data types are ignored in Java.</li>";
		s += "<li>Sensitive similarity considers all tokens as they are without generalisation.</li>";
		s = s + "</ul>\n";

		return s;
	}

	public static String getAboutEn() {
		return "<ol>\r\n"
				+ "				<li>This HTML page is generated by SSTRANGE, a scalable and efficient tool to observe similarities among submissions with locality sensitive hashing. The details can be seen in <b><u><a href = \"https://github.com/oscarkarnalim/sstrange\">the Github page</a></u></b> or <b><u><a href=\"https://www.mdpi.com/2227-7102/13/1/54\">the corresponding publication</a></u></b></li>\r\n"
				+ "				<li>If you want to cite the program (or some parts of it), please cite the corresponding publication. </li>\r\n"
				+ "				</ol>";
	}

	public static String getAboutID() {
		return "<ol>\r\n"
				+ "				<li>Laman HTML ini dibuat dengan SSTRANGE, sebuah kakas skalabel dan efisien untuk mengobservasi kesamaan antar tugas dengan locality sensitive hashing. Detil dapat dilihat di <b><u><a href = \"https://github.com/oscarkarnalim/sstrange\">laman Github</a></u></b> atau <b><u><a href=\"https://www.mdpi.com/2227-7102/13/1/54\">publikasi terkait</a></u></b></li>\\r\\n"
				+ "				<li>Jika kamu ingin mensitasi program ini (atau bagian-bagiannya), mohon sitasi publikasi terkait. </li>\r\n"
				+ "				</ol>";
	}

	private static String getTableContent(ArrayList<ComparisonPairTuple> codePairs, String languageCode) {
		String textForObserve = "observe";
		if (languageCode.equals("id"))
			textForObserve = "amati";

		String s = "";
		int numID = 0;
		for (ComparisonPairTuple ct : codePairs) {
			// generate the ID
			String entryID = "r" + numID;

			// generate the string
			s += "<tr id=\"" + entryID + "\" onclick=\"selectRow('" + entryID + "','sumtablecontent')\">";
			s += ("\n\t<td><a>" + ct.getAssignmentName1() + "-" + ct.getAssignmentName2() + "</a></td>");
			s += ("\n\t<td>" + String.format("%.0f", ct.getSyntaxSimResult()) + " %</td>");
			if (ct.getSurfaceSimResult() != -1)
				// if surface is calculated, the overall result is printed here
				s += ("\n\t<td>" + String.format("%.0f",ct.getSimResult()) + "%</td>");
			else
				s += ("\n\t<td>NA</td>");

			s += ("\n\t<td><button onclick=\"window.open('" + ct.getResultedHTMLFilename() + "', '_self');\">"
					+ textForObserve + "</button></td>");
			s += "\n</tr>\n";

			// increment number for ID
			numID++;
		}
		return s;
	}
}
